// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(["jslib/leaflet", "./linelayer"], function(leaflet, LineLayer) {
    var MapDisplay;
    return MapDisplay = (function() {

      function MapDisplay(target) {
        this.drawLine = __bind(this.drawLine, this);

        var tileLayer;
        this.mapEl = target;
        this.map = L.map(this.mapEl[0]).setView([37, 0], 2);
        tileLayer = L.tileLayer('http://{s}.tiles.mapbox.com/v3/alastaircoote.map-n7irpmld/{z}/{x}/{y}.png', {
          maxZoom: 18
        });
        tileLayer.addTo(this.map);
      }

      MapDisplay.prototype.drawLine = function(from, to, hue) {
        var Lfrom, Lto, layer;
        Lfrom = new L.LatLng(from.lat, from.lng);
        Lto = new L.LatLng(to.lat, to.lng);
        layer = new LineLayer(Lfrom, Lto, hue);
        return this.map.addLayer(layer);
      };

      return MapDisplay;

    })();
  });

}).call(this);
